### ISSUE TITLE
Check not matching armv7 hosts

### ISSUE THREAD

**Issue by sawasy** [asachs01/sensu-go-cpu-check#1]
This doesn't seem to be matching my `arm` machines out of the box.
```
$ uname -m    
armv7l
```

I am seeing the following in the agent logs on the arm machine.
`entity not filtered from any asset builds, not installing asset`

For the machine, I see:

```
$ sensuctl entity info <hostname> --format json
[...]
  "system": {
[...]
    "os": "linux",
    "platform": "raspbian",
    "platform_family": "debian",
    "platform_version": "10.4",
[...]
    "arch": "arm",
    "arm_version": 7,
[...]
```

I think .bonsai.yml this needs to be updated from:
```
- platform: "linux"
  arch: "armv7"
  asset_filename: "#{repo}_#{version}_linux_armv7.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'armv7'"
```

to 

```
- platform: "linux"
  arch: "armv7"
  asset_filename: "#{repo}_#{version}_linux_armv7.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'arm'"
  -  "entity.system.arm_version" == "7"
```

Cheers

m!
